
import Activites from '@/components/Activites'
import Booking from '@/components/Booking'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Gallery from '@/components/Gallery'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Topbar from '@/components/Topbar'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Topbar />

      <Navbar />

      <Hero />

      <Activites />

      <Booking />

      <Gallery />

      <Contact />

      <Footer />
     
     


    </>
  )
}
